CREATE TABLE categories (
   @NORMALINTEGER id INTEGER UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT, 
   @NORMALSTRING name VARCHAR(50),
   PRIMARY KEY(id)
);

CREATE TABLE regions (
   @NORMALINTEGER id INTEGER UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
   @NORMALSTRING name VARCHAR(25),
   PRIMARY KEY(id)
);

@AUSETTABLE CREATE TABLE users (
   @NORMALINTEGER id INTEGER UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
   @NORMALSTRING firstname     VARCHAR(20),
   @NORMALSTRING lastname      VARCHAR(20),
   @NORMALSTRING nickname      VARCHAR(20) NOT NULL UNIQUE,
   @NORMALSTRING password      VARCHAR(20) NOT NULL,
   @NORMALSTRING email         VARCHAR(50) NOT NULL,
   @LWWINTEGER rating        INTEGER,
   @NORMALFLOAT balance       FLOAT,
   @NORMALDATETIME creation_date DATETIME, 
   @NORMALINTEGER region        INTEGER UNSIGNED NOT NULL,
   PRIMARY KEY(id),
   INDEX auth (nickname,password),
   INDEX region_id (region)
);

@AUSETTABLE CREATE TABLE items (
   @NORMALINTEGER id            INTEGER UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
   @NORMALSTRING name          VARCHAR(100),
   @NORMALSTRING description   TEXT,
   @NORMALFLOAT initial_price FLOAT UNSIGNED NOT NULL,
   @NUMDELTAINTEGER quantity      INTEGER UNSIGNED NOT NULL,
   @LWWFLOAT reserve_price FLOAT UNSIGNED DEFAULT 0,
   @LWWFLOAT buy_now       FLOAT UNSIGNED DEFAULT 0,
   @NUMDELTAINTEGER nb_of_bids    INTEGER UNSIGNED DEFAULT 0,
   @LWWFLOAT max_bid       FLOAT UNSIGNED DEFAULT 0,
   @NORMALDATETIME start_date    DATETIME,    
   @LWWDATETIME end_date      DATETIME,
   @NORMALINTEGER seller        INTEGER UNSIGNED NOT NULL,
   @NORMALINTEGER category      INTEGER UNSIGNED NOT NULL,
   PRIMARY KEY(id),
   INDEX seller_id (seller),
   INDEX category_id (category)
);

@AOSETTABLE CREATE TABLE bids (
   @NORMALINTEGER id      INTEGER UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
   @NORMALINTEGER user_id INTEGER UNSIGNED NOT NULL,
   @NORMALINTEGER item_id INTEGER UNSIGNED NOT NULL,
   @NORMALINTEGER qty     INTEGER UNSIGNED NOT NULL,
   @NORMALFLOAT bid     FLOAT UNSIGNED NOT NULL,
   @NORMALFLOAT max_bid FLOAT UNSIGNED NOT NULL,
   @NORMALDATETIME date    DATETIME, 
   PRIMARY KEY(id),
   INDEX item (item_id),
   INDEX user (user_id)
);

@AOSETTABLE CREATE TABLE comments (
   @NORMALINTEGER id           INTEGER UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
   @NORMALINTEGER from_user_id INTEGER UNSIGNED NOT NULL,
   @NORMALINTEGER to_user_id   INTEGER UNSIGNED NOT NULL,
   @NORMALINTEGER item_id      INTEGER UNSIGNED NOT NULL,
   @NORMALINTEGER rating       INTEGER,
   @NORMALDATETIME date        DATETIME,    
   @NORMALSTRING comment      TEXT,
   PRIMARY KEY(id),
   INDEX from_user (from_user_id),
   INDEX to_user (to_user_id),
   INDEX item (item_id)
);

@AOSETTABLE CREATE TABLE buy_now (
   @NORMALINTEGER id       INTEGER UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
   @NORMALINTEGER buyer_id INTEGER UNSIGNED NOT NULL,
   @NORMALINTEGER item_id  INTEGER UNSIGNED NOT NULL,
   @NORMALINTEGER qty      INTEGER UNSIGNED NOT NULL,
   @NORMALDATETIME date    DATETIME,
   PRIMARY KEY(id),
   INDEX buyer (buyer_id),
   INDEX item (item_id)
);
